export const insults = [
  "Dumb ass",
  "How long have you been shooting?",
  "Is your site mark set to stupid?",
  "Maybe you should just go home",
  "Throw your beaux in the bin",
  "You're not even trying",
  "You are a danger to yourself and others",
  "Are your eyes open",
  "Your aim is as good as your jokes.",
  "Are you aiming for a different universe?",
  "You couldn't hit water if you fell out of a boat",
  "Is this some kind of abstract art?",
  "Nice shot! For someone who hates hitting the target",
  "You're redefining what it means to miss",
  "Are you allergic to accuracy?",
  "There's always next year",
  "Everyone hates finding your arrows but are being too polite about it",
  "We'd be speaking French if you were at the battle of Agincourt",
  "You are Tesco value robin hood",
  "Maybe try the beginner's course again",
  "We cant kick you out of the club for being bad, but we'll find another reason",
  "Did you know you are supposed to hit the target?",
  "Maybe next time",
  "I shoot better and I am just a phone, with no ability to pick up a beaux",
  "Did you trip over the line when you were at full draw?",
  "I've seen better shooting by a 2 week old baby.",
  "We've had to check with the farm how much it would cost to replace a sheep because of your shooting.",
  "It's very kind of you to save the target face from wear and tear.",
  "That was not very good.",
  "I hope you shoot better photos than you do arrows",
  "When you went to draw your beaux, did you take out a crayon?",
  "Is your anchor at your arse?",
  "We all have off days. But you seem to have off years.",
  "Did you find your anchor on a boat?",
  "Are the limbs the right way round?",
  "Is your bracing height a negative number?",
  "Have you replaced your button with the button from your shirt",
  "It might have been better to dry fire that one",
  "Here's a solution to target panic, stop panicking",
  "Peter André wrote Mysterious girl about you, because you keep missing",
  "If you do that again at the next end, it's you",
  "I thought the sheep had been in this field but it was just your arrow",
  "I have a joke for you. What's the difference between you and the sheep? Nothing, you both stink at archery",
  "Did you tune your beaux with a banana?",
  "I want to be a positive coach, but i just cant with you",
  "Your beaux is so out of tune I thought it was a sheep coughing.",
  "You're not supposed to tune your beaux to D sharp",
  "I'm not sure the metal detectors can find your arrows, because you are shooting poops",
  "Archery GB are introducing archer 4 classification, just for you",
  "There are no badges for scoring 50 in 3 dozen arrows",
  "That was a good shot, for a longbow, at 200 yards, in the dark, during an earthquake",
  "Please don't offer advice to anyone, ever",
  "Your boss mate doesn't need to worry about their arrows getting damaged",
  "Nice gear; it's a shame you can't buy talent",
  "Changing your arrows wont make a difference, because you are very bad",
  "Don't bother upgrading your equipment, upgrade your brain",
  "The club members won’t laugh at you, but I will ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha",
  "Thank you for becoming a member of the spider conservation society",
  "What do you call an archer who never misses? Not you.",
  "Is your favourite musical artist Missy Elliott?",
  "Next time shoot your arrow and we'll paint the target around it",
  "Have you ever tried blind-folded archery? You don't know what you're missing",
  "Your favourite Mister men character is Mister miss",
  "Nice try! Were you aiming for the moon?",
  "You should change your name to Robin Hoodwinked.",
  "I thought this was archery, not a comedy show.",
  "If you aimed for disappointment, then congratulations!",
  "Even a stopped clock hits the target twice a day.",
  "You’re shooting blanks with actual arrows.",
  "You’re the Picasso of archery – abstract and confusing.",
  "Your arrows are writing their own adventure stories."
];